blockio_api_doge_key = "blockio_api_key for doge"
blockio_api_btc_key = "blockio_api_key for btc"
blockio_api_ltc_key = "blockio_api_key for ltc"
blockio_secret_pin = "blockio_secret_pin"
slack_token = "slackAPItoken"
